### ISSUE TITLE
Load Error when rails app uses an engine

### ISSUE THREAD

**Issue by bradseefeld** [lonelyplanet/fozzie#18]
I _think_ this is isolated to when the rails application is using an engine, but it may be more broad than that. The error:

````
LoadError (Expected app/controllers/application_controller.rb to define ApplicationController):
  app/controllers/application_controller.rb:1:in `<top (required)>'
  app/controllers/audits_controller.rb:1:in `<top (required)>'
````

The controller:

````
class ApplicationController < MyEngine::ApplicationController
  ...
end
````

When I change it to extend from `ActionController::Base` things work just fine. I imagine this has to do with the load order for fozzie vs my engine?

When I dont include the fozzie gem, things work fine. I have tested on all published versions of fozzie as well as checking out master.

**Comment by robuye** [comment]
It's fixed, new versions have been pushed to rubygems.

Thanks for the report and apologies for huge delay.
